### ISSUE TITLE
Backend: Script to insert data not including coop email address

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#155]
When we import data from the Google spreadsheet (https://docs.google.com/spreadsheets/d/1ifpqYM0uV1S3YVPrce5gmvevJ7jc-cFmOk5jDS8Me7U/edit#gid=0) into our database, a process that is done by running the following commands

If you are running docker, run
```
docker-compose exec web sh
python manage.py init_from_google_sheet > /tmp/output.csv
python manage.py parse_coop_csv /tmp/output.csv > /tmp/seed_data.yaml
python manage.py insert_seed_data /tmp/seed_data.yaml true
```

Without docker, run

```
cd web
. venv/bin/activate
venv/bin/python manage.py init_from_google_sheet > /tmp/output.csv
venv/bin/python manage.py parse_coop_csv /tmp/output.csv > /tmp/seed_data.yaml
venv/bin/python manage.py insert_seed_data /tmp/seed_data.yaml true
```

the script that generates the "seed_data.yml" file (the second to last command above), fails to generate an entry for the email address.  For example, a line in the CSV that looks like

```
"97","Bleux Financial Solutions Inc.","1751D W Howard Street #254","yes","60626","Chicago","Cook","IL","USA","https://bleux.net","Dan Cappy","no","daniel@bleux.net","no","855.253.8937","yes","Workers Collective","yes","address","both","local","","","","","","","","","Christopher Preciado","SE","2021-04-30"
```

currently produces data like this that goes into the yml file,

```
- model: directory.contactmethod
  pk: 195
  fields:
    type: "PHONE"
    phone: 855.253.8937
- model: directory.coop
  pk: 97
  fields:
    name: "Bleux Financial Solutions Inc."
    types:
    - ['Workers Collective']
    addresses: [ 94 ]
    enabled: True
    phone: 195
    web_site: "https://bleux.net"
```

but it should also include data to include the email, so it would probably need to look like this

```
- model: directory.contactmethod
  pk: (some number)
  fields:
    type: "EMAIL"
    email: daniel@bleux.net
- model: directory.contactmethod
  pk: 195
  fields:
    type: "PHONE"
    phone: 855.253.8937
- model: directory.coop
  pk: 97
  fields:
    name: "Bleux Financial Solutions Inc."
    types:
    - ['Workers Collective']
    addresses: [ 94 ]
    enabled: True
    phone: 195
    web_site: "https://bleux.net"
```
