### ISSUE TITLE
Backend: Adjust data import script to accommodate new address model

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#209]
You will want to be on our authentication branch for this

```
git checkout authentication
```

When we run the script to generate our seed data from the Google spreadsheet

```
cd web
. venv/bin/activate
python manage.py init_from_google_sheet > /tmp/output.csv
python manage.py parse_coop_csv /tmp/output.csv > /tmp/seed_data.yaml 
```

We need to change the way the coop entity is output in the file "seed_data.yaml" from this

```
- model: directory.coop
  pk: 824
  fields:
    name: "Win-Hood Co-Op Credit Union"
    types:
    - ['Credit Union']
    addresses: [ 785 ]
    enabled: True
    phone: 1649
    web_site: "http://winhoodcu.com/"
    approved: True
```

to this (note that we have two models now, the coop, and an addresstags entity that ties the coop back to an address) ...

```
- model: directory.coop
  pk: 824
  fields:
    name: "Win-Hood Co-Op Credit Union"
    types:
    - ['Credit Union']
    enabled: True
    phone: 1649
    web_site: "http://winhoodcu.com/"
    approved: True

- model: directory.addresstag
  pk: <come up with some unique number here>
  fields:
    is_public: <True/False (value will come from [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1ifpqYM0uV1S3YVPrce5gmvevJ7jc-cFmOk5jDS8Me7U/edit#gid=0))>
    coop_id: 824
    address_id: 785
```

This will allow us to import from the Google Spreadsheet into our new database format
