### ISSUE TITLE
Backend: Import script needs to properly represent multiple contacts

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#225]
If you check out the authentication branch

```
git checkout authentication
```

and then rebuild your Docker containers, you'll notice we now can support multiple emails/phone contacts per entity.  The trouble is, when our script runs, it is currently generating data using a single ID format, e.g.

```
- model: directory.coop
  pk: 854
  fields:
    name: "The Collective Yoga Co-op"
    types:
    - ['Workers Collective']
    addresses: [ 769 ]
    enabled: True
    email: 1708
    web_site: "thecollectiveyogacoop.com"
```

Notice above "email" has a single number, representing the id of the contact for email.  However, the format above needs to change to

```
- model: directory.coop
  pk: 854
  fields:
    name: "The Collective Yoga Co-op"
    types:
    - ['Workers Collective']
    addresses: [ 769 ]
    enabled: True
    email: [1708]
    web_site: "thecollectiveyogacoop.com"
```

Similarly, entities that represent a phone contact as a single phone number, need to change to have thte brackets.  So this

```
- model: directory.coop
  pk: 824
  fields:
    name: "Win-Hood Co-Op Credit Union"
    types:
    - ['Credit Union']
    addresses: [ 748 ]
    enabled: True
    phone: 1649
    web_site: "http://winhoodcu.com/"
    approved: True
```

need to change to this

```
- model: directory.coop
  pk: 824
  fields:
    name: "Win-Hood Co-Op Credit Union"
    types:
    - ['Credit Union']
    addresses: [ 748 ]
    enabled: True
    phone: [1649]
    web_site: "http://winhoodcu.com/"
    approved: True
```

As a reminder, to run the script, run these commands locally

```
. venv/bin/activate
python manage.py init_from_google_sheet > /tmp/output.csv
python manage.py parse_coop_csv /tmp/output.csv > /tmp/seed_data.yaml
python manage.py insert_seed_data /tmp/seed_data.yaml true
```
