### ISSUE TITLE
Incorrect YAML (seed data) generated when a coop has multiple types

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#35]
Currently, if we have data like the below

```
242,243,Dill Pickle Food Co-op,3039 W Fullerton Ave,yes,60647,Chicago,,IL,USA,Cooperative,yes,address,both,local,dillpickle.coop,,,,,,,,,,,,-87.70345846,41.92466218,Shareable Map,SE,2020-12-26
845,845,Dill Pickle Food Co-op,IL 60647,yes,60647,Chicago,Cook,IL,USA,food coop,check,,,,http://dillpickle.coop,,,,,,,,,,,,-87.701028,41.921215,dotcoop,SE,12/26/20

```
It will produce YAML like so

```
 pk: 243
  fields:
    name: "Dill Pickle Food Co-op"
    types:
    - ['Cooperative', 'food coop']

```
Unfortunately, this results in errors because the YAML is malformed.  For multiple types, the YAML needs to look like

```
 pk: 243
  fields:
    name: "Dill Pickle Food Co-op"
    types:
    - ['Cooperative']
    - ['food coop']

```
I believe these lines in the scirpt are the culprit ... . 

```
                    print("    types:")
                    print("    - ['", "','".join(types), "']", sep='')

```
