### ISSUE TITLE
Allow seed data even if there are no valid coordinates

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#38]
Currently, our web/directory/management/commands/parse_coop_csv.py script will not output results if there is not a corresponding latitude or longitude returned from our Geocoder location service.  We now have a page in our React application ...

https://prod.chicommons.coop/nocoords

that will alert administrators which coops do not currently have valid, mappable addresses, so it is fine now for the script to output the address data even if no coordinates are found.  The seed output can simply exclude the "latitude" and "longitude" columns, so it could look like

```
- model: address.address
  pk: 1
  fields:
    street_number: 222
    route: 1212
    raw: 222 W. Merchandise Mart Plaza, Suite 1212
    formatted: 222 W. Merchandise Mart Plaza, Suite 1212
    locality: 1
```

as an example.
